// Generated by scripts/generate-free-routes.ts — do not edit.
import type { Deployment, RouteGroup } from "./schema";
import type { FreeCatalogSuggestions } from "../ops/sync-free-models";

export const FREE_ROUTES_FINGERPRINT = "d324a5a83225515af87f87ff87d2d6377ce76be0b3c07ce62d76e5e81edc674c";

export const FREE_ROUTES_PROVIDERS_ENABLED: FreeCatalogSuggestions["providersEnabled"] = {
  "openrouter": true,
  "groq": false,
  "nim": true,
  "kilo": true,
  "opencodeZen": true
};

export const FREE_ROUTE_GROUPS: Record<string, RouteGroup> = {
  "free": {
    "target": "free-kilo",
    "hidden": false,
    "fallbacks": [
      "free-opencode-zen",
      "free-openrouter",
      "nim-deepseek-v4-pro",
      "nim-kimi-k2.5",
      "nim-minimax-m2.7",
      "nim-primary",
      "nim-tool-primary"
    ],
    "billingClass": "free"
  },
  "free-kilo": {
    "target": "free-kilo",
    "hidden": false,
    "fallbacks": [],
    "billingClass": "free",
    "modelPassthrough": true
  },
  "free-opencode-zen": {
    "target": "free-opencode-zen",
    "hidden": false,
    "fallbacks": [],
    "billingClass": "free",
    "modelPassthrough": true
  },
  "free-openrouter": {
    "target": "free-openrouter",
    "hidden": false,
    "fallbacks": [],
    "billingClass": "free",
    "modelPassthrough": true
  }
};

export const FREE_ROUTE_ALIASES: Record<string, string> = {
  "free": "free",
  "freemium": "free",
  "baidu/cobuddy:free": "free",
  "deepseek/deepseek-v4-flash:free": "free",
  "kilo-auto/free": "free",
  "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": "free",
  "nvidia/nemotron-3-super-120b-a12b:free": "free",
  "openrouter/free": "free",
  "openrouter/owl-alpha": "free",
  "poolside/laguna-m.1:free": "free",
  "poolside/laguna-xs.2:free": "free",
  "x-ai/grok-code-fast-1:optimized:free": "free",
  "deepseek-v4-flash-free": "free",
  "nemotron-3-super-free": "free",
  "arcee-ai/trinity-large-thinking:free": "free",
  "cognitivecomputations/dolphin-mistral-24b-venice-edition:free": "free",
  "google/gemma-4-26b-a4b-it:free": "free",
  "google/gemma-4-31b-it:free": "free",
  "liquid/lfm-2.5-1.2b-instruct:free": "free",
  "liquid/lfm-2.5-1.2b-thinking:free": "free",
  "meta-llama/llama-3.2-3b-instruct:free": "free",
  "meta-llama/llama-3.3-70b-instruct:free": "free",
  "minimax/minimax-m2.5:free": "free",
  "nousresearch/hermes-3-llama-3.1-405b:free": "free",
  "nvidia/nemotron-3-nano-30b-a3b:free": "free",
  "nvidia/nemotron-nano-12b-v2-vl:free": "free",
  "nvidia/nemotron-nano-9b-v2:free": "free",
  "openai/gpt-oss-120b:free": "free",
  "openai/gpt-oss-20b:free": "free",
  "qwen/qwen3-coder:free": "free",
  "qwen/qwen3-next-80b-a3b-instruct:free": "free",
  "z-ai/glm-4.5-air:free": "free"
};

export const FREE_ROUTE_DEPLOYMENTS: Deployment[] = [
  {
    "provider": "openai",
    "model": "baidu-cobuddy-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-baidu-cobuddy-free",
    "group": "free-kilo",
    "providerModel": "baidu/cobuddy:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "deepseek-deepseek-v4-flash-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-deepseek-deepseek-v4-flash-free",
    "group": "free-kilo",
    "providerModel": "deepseek/deepseek-v4-flash:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": false
  },
  {
    "provider": "openai",
    "model": "kilo-auto-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-kilo-auto-free",
    "group": "free-kilo",
    "providerModel": "kilo-auto/free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": false
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-3-nano-omni-30b-a3b-reasoning-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-nvidia-nemotron-3-nano-omni-30b-a3b-reasoning-free",
    "group": "free-kilo",
    "providerModel": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-3-super-120b-a12b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-nvidia-nemotron-3-super-120b-a12b-free",
    "group": "free-kilo",
    "providerModel": "nvidia/nemotron-3-super-120b-a12b:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "openrouter-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-openrouter-free",
    "group": "free-kilo",
    "providerModel": "openrouter/free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "openrouter-owl-alpha",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-openrouter-owl-alpha",
    "group": "free-kilo",
    "providerModel": "openrouter/owl-alpha",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "poolside-laguna-m-1-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-poolside-laguna-m-1-free",
    "group": "free-kilo",
    "providerModel": "poolside/laguna-m.1:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "poolside-laguna-xs-2-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-poolside-laguna-xs-2-free",
    "group": "free-kilo",
    "providerModel": "poolside/laguna-xs.2:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "x-ai-grok-code-fast-1-optimized-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-kilo-x-ai-grok-code-fast-1-optimized-free",
    "group": "free-kilo",
    "providerModel": "x-ai/grok-code-fast-1:optimized:free",
    "keyRef": "KILO_API_KEY_1",
    "apiBase": "https://api.kilo.ai/api/gateway",
    "freeTier": "kilo_gateway",
    "credentialOptional": false
  },
  {
    "provider": "openai",
    "model": "deepseek-v4-flash-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-zen-deepseek-v4-flash-free",
    "group": "free-opencode-zen",
    "providerModel": "deepseek-v4-flash-free",
    "keyRef": "OPENCODE_API_KEY_1",
    "apiBase": "https://opencode.ai/zen/v1",
    "freeTier": "opencode_zen",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "nemotron-3-super-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-zen-nemotron-3-super-free",
    "group": "free-opencode-zen",
    "providerModel": "nemotron-3-super-free",
    "keyRef": "OPENCODE_API_KEY_1",
    "apiBase": "https://opencode.ai/zen/v1",
    "freeTier": "opencode_zen",
    "credentialOptional": true
  },
  {
    "provider": "openai",
    "model": "arcee-ai-trinity-large-thinking-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-arcee-ai-trinity-large-thinking-free",
    "group": "free-openrouter",
    "providerModel": "arcee-ai/trinity-large-thinking:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "baidu-cobuddy-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-baidu-cobuddy-free",
    "group": "free-openrouter",
    "providerModel": "baidu/cobuddy:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "cognitivecomputations-dolphin-mistral-24b-venice-edition-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-cognitivecomputations-dolphin-mistral-24b-venice-edition-free",
    "group": "free-openrouter",
    "providerModel": "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "deepseek-deepseek-v4-flash-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-deepseek-deepseek-v4-flash-free",
    "group": "free-openrouter",
    "providerModel": "deepseek/deepseek-v4-flash:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "google-gemma-4-26b-a4b-it-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-google-gemma-4-26b-a4b-it-free",
    "group": "free-openrouter",
    "providerModel": "google/gemma-4-26b-a4b-it:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "google-gemma-4-31b-it-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-google-gemma-4-31b-it-free",
    "group": "free-openrouter",
    "providerModel": "google/gemma-4-31b-it:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "liquid-lfm-2-5-1-2b-instruct-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-liquid-lfm-2-5-1-2b-instruct-free",
    "group": "free-openrouter",
    "providerModel": "liquid/lfm-2.5-1.2b-instruct:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "liquid-lfm-2-5-1-2b-thinking-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-liquid-lfm-2-5-1-2b-thinking-free",
    "group": "free-openrouter",
    "providerModel": "liquid/lfm-2.5-1.2b-thinking:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "meta-llama-llama-3-2-3b-instruct-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-meta-llama-llama-3-2-3b-instruct-free",
    "group": "free-openrouter",
    "providerModel": "meta-llama/llama-3.2-3b-instruct:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "meta-llama-llama-3-3-70b-instruct-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-meta-llama-llama-3-3-70b-instruct-free",
    "group": "free-openrouter",
    "providerModel": "meta-llama/llama-3.3-70b-instruct:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "minimax-minimax-m2-5-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-minimax-minimax-m2-5-free",
    "group": "free-openrouter",
    "providerModel": "minimax/minimax-m2.5:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nousresearch-hermes-3-llama-3-1-405b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nousresearch-hermes-3-llama-3-1-405b-free",
    "group": "free-openrouter",
    "providerModel": "nousresearch/hermes-3-llama-3.1-405b:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-3-nano-30b-a3b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nvidia-nemotron-3-nano-30b-a3b-free",
    "group": "free-openrouter",
    "providerModel": "nvidia/nemotron-3-nano-30b-a3b:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-3-nano-omni-30b-a3b-reasoning-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nvidia-nemotron-3-nano-omni-30b-a3b-reasoning-free",
    "group": "free-openrouter",
    "providerModel": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-3-super-120b-a12b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nvidia-nemotron-3-super-120b-a12b-free",
    "group": "free-openrouter",
    "providerModel": "nvidia/nemotron-3-super-120b-a12b:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-nano-12b-v2-vl-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "native"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nvidia-nemotron-nano-12b-v2-vl-free",
    "group": "free-openrouter",
    "providerModel": "nvidia/nemotron-nano-12b-v2-vl:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "nvidia-nemotron-nano-9b-v2-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-nvidia-nemotron-nano-9b-v2-free",
    "group": "free-openrouter",
    "providerModel": "nvidia/nemotron-nano-9b-v2:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "openai-gpt-oss-120b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-openai-gpt-oss-120b-free",
    "group": "free-openrouter",
    "providerModel": "openai/gpt-oss-120b:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "openai-gpt-oss-20b-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-openai-gpt-oss-20b-free",
    "group": "free-openrouter",
    "providerModel": "openai/gpt-oss-20b:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "openrouter-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-openrouter-free",
    "group": "free-openrouter",
    "providerModel": "openrouter/free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "openrouter-owl-alpha",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-openrouter-owl-alpha",
    "group": "free-openrouter",
    "providerModel": "openrouter/owl-alpha",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "poolside-laguna-m-1-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-poolside-laguna-m-1-free",
    "group": "free-openrouter",
    "providerModel": "poolside/laguna-m.1:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "poolside-laguna-xs-2-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-poolside-laguna-xs-2-free",
    "group": "free-openrouter",
    "providerModel": "poolside/laguna-xs.2:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "qwen-qwen3-coder-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-qwen-qwen3-coder-free",
    "group": "free-openrouter",
    "providerModel": "qwen/qwen3-coder:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "qwen-qwen3-next-80b-a3b-instruct-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-qwen-qwen3-next-80b-a3b-instruct-free",
    "group": "free-openrouter",
    "providerModel": "qwen/qwen3-next-80b-a3b-instruct:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  },
  {
    "provider": "openai",
    "model": "z-ai-glm-4-5-air-free",
    "rpm": 20,
    "maxParallelRequests": 1,
    "timeout": 500,
    "streamTimeout": 500,
    "supportsStreaming": true,
    "capabilities": {
      "toolCalling": "best_effort",
      "streamingWithTools": "best_effort",
      "jsonMode": "native",
      "reasoning": "none",
      "multimodal": "none"
    },
    "contextWindow": 128000,
    "hidden": false,
    "billingClass": "free",
    "params": {
      "temperature": 0.7,
      "top_p": 0.95
    },
    "id": "free-or-z-ai-glm-4-5-air-free",
    "group": "free-openrouter",
    "providerModel": "z-ai/glm-4.5-air:free",
    "keyRef": "OPENROUTER_API_KEY_1",
    "apiBase": "https://openrouter.ai/api/v1",
    "freeTier": "catalog_zero",
    "extraBody": {
      "HTTP-Referer": "https://github.com/jroth1111/switchboard",
      "X-Title": "switchboard"
    }
  }
];

export const FREE_ROUTE_POLICY_NAMES = [
  "free",
  "free-kilo",
  "free-opencode-zen",
  "free-openrouter",
  "free-groq",
] as const;
