#!/usr/bin/env node
/**
 * Build src/config/free-routes.generated.ts from sync-free-models-suggestions.json + env keys.
 */
import { readFileSync, writeFileSync } from "node:fs";
import {
  isChatCompletionsFreeCatalogCandidate,
  type FreeCatalogSuggestions,
} from "../src/ops/sync-free-models.ts";
import { buildFreeDeployments, buildFreeRouteGroups } from "../src/config/build-free-routes.ts";
import { loadLocalSecretEnv } from "./chatgpt-auth-secrets.ts";

const SUGGESTIONS_PATH = process.env.SUGGESTIONS_PATH ?? "config/sync-free-models-suggestions.json";
const OUT_PATH = "src/config/free-routes.generated.ts";

function main() {
  const localSecrets = loadLocalSecretEnv();
  const env = { ...localSecrets.values, ...process.env } as Record<string, unknown>;
  const raw = readFileSync(SUGGESTIONS_PATH, "utf8");
  const parsed = JSON.parse(raw) as FreeCatalogSuggestions;
  const catalog: FreeCatalogSuggestions = {
    ...parsed,
    models: parsed.models.filter((m) => isChatCompletionsFreeCatalogCandidate(m.modelId)),
  };

  const providersEnabled = catalog.providersEnabled;
  const mergedCatalog: FreeCatalogSuggestions = { ...catalog, providersEnabled };
  const { deployments, aliases } = buildFreeDeployments(mergedCatalog, env);
  const routeGroups = buildFreeRouteGroups(mergedCatalog);

  const body = `// Generated by scripts/generate-free-routes.ts — do not edit.
import type { Deployment, RouteGroup } from "./schema";
import type { FreeCatalogSuggestions } from "../ops/sync-free-models";

export const FREE_ROUTES_FINGERPRINT = ${JSON.stringify(catalog.fingerprint)};

export const FREE_ROUTES_PROVIDERS_ENABLED: FreeCatalogSuggestions["providersEnabled"] = ${JSON.stringify(providersEnabled, null, 2)};

export const FREE_ROUTE_GROUPS: Record<string, RouteGroup> = ${JSON.stringify(routeGroups, null, 2)};

export const FREE_ROUTE_ALIASES: Record<string, string> = ${JSON.stringify(aliases, null, 2)};

export const FREE_ROUTE_DEPLOYMENTS: Deployment[] = ${JSON.stringify(deployments, null, 2)};

export const FREE_ROUTE_POLICY_NAMES = [
  "free",
  "free-kilo",
  "free-opencode-zen",
  "free-openrouter",
  "free-groq",
] as const;
`;

  writeFileSync(OUT_PATH, body);
  console.log(
    `Wrote ${OUT_PATH}: ${deployments.length} deployments, ${Object.keys(aliases).length} aliases, `
    + `fallbacks=${routeGroups.free?.fallbacks?.length ?? 0}, providers=${JSON.stringify(providersEnabled)}`,
  );
}

main();
